#!/bin/bash
echo "=================================================="
echo "BIENVENIDO A LA DEMO DE PATRONES DE DISEÑO"
echo "=================================================="
echo ""
echo "[INFO] Esta aplicación demuestra tres patrones de diseño clásicos:"
echo "  - Template Method: Estructura de algoritmos"
echo "  - Decorator: Agregar funcionalidades dinámicamente"
echo "  - Factory Method: Creación de objetos delegada"
echo ""
sleep 2

echo "=================================================="
echo "DEMO PATRONES DE DISEÑO"
echo "=================================================="
echo ""

echo "================================"
echo "       MENÚ PRINCIPAL        "
echo "================================"
echo ""
echo "1. Template Method"
echo "   Define la estructura de un algoritmo"
echo "   y delega detalles a subclases"
echo ""
echo "2. Decorator"
echo "   Agrega funcionalidades dinámicamente"
echo ""
echo "3. Factory Method"
echo "   Delega la creación de objetos a subclases"
echo ""
echo "4. Salir"
echo ""

echo "Presiona cualquier tecla para seleccionar..."
read -n 1 -s
echo ""

clear

echo "=================================================="
echo "BIENVENIDO A LA DEMO DE PATRONES DE DISEÑO"
echo "=================================================="
echo ""
echo "[INFO] Esta aplicación demuestra tres patrones de diseño clásicos:"
echo "  - Template Method: Estructura de algoritmos"
echo "  - Decorator: Agregar funcionalidades dinámicamente"
echo "  - Factory Method: Creación de objetos delegada"
echo ""
sleep 1

echo "=================================================="
echo "DEMO PATRONES DE DISEÑO"
echo "=================================================="
echo ""
echo "================================"
echo "       MENÚ PRINCIPAL        "
echo "================================"
echo ""
echo "1. Template Method"
echo "   Define la estructura de un algoritmo"
echo "   y delega detalles a subclases"
echo ""
echo "2. Decorator"
echo "   Agrega funcionalidades dinámicamente"
echo ""
echo "3. Factory Method"
echo "   Delega la creación de objetos a subclases"
echo ""
echo "4. Salir"
echo ""

echo "Presiona cualquier tecla para seleccionar..."
read -n 1 -s
